version: '3'
services:
  LAMP:
    image: 25sprout/lamp:8-2.4-10.1-7.2
    ports:
      - '5580:80'
    volumes:
      - ./html:/var/www/html
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123qweasd
      - MYSQL_DATABASE=SurveyCake2S
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
